// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/flight.proto

package fbspb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// FlightBookingSystemServiceClient is the client API for FlightBookingSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightBookingSystemServiceClient interface {
}

type flightBookingSystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightBookingSystemServiceClient(cc grpc.ClientConnInterface) FlightBookingSystemServiceClient {
	return &flightBookingSystemServiceClient{cc}
}

// FlightBookingSystemServiceServer is the server API for FlightBookingSystemService service.
// All implementations must embed UnimplementedFlightBookingSystemServiceServer
// for forward compatibility.
type FlightBookingSystemServiceServer interface {
	mustEmbedUnimplementedFlightBookingSystemServiceServer()
}

// UnimplementedFlightBookingSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightBookingSystemServiceServer struct{}

func (UnimplementedFlightBookingSystemServiceServer) mustEmbedUnimplementedFlightBookingSystemServiceServer() {
}
func (UnimplementedFlightBookingSystemServiceServer) testEmbeddedByValue() {}

// UnsafeFlightBookingSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightBookingSystemServiceServer will
// result in compilation errors.
type UnsafeFlightBookingSystemServiceServer interface {
	mustEmbedUnimplementedFlightBookingSystemServiceServer()
}

func RegisterFlightBookingSystemServiceServer(s grpc.ServiceRegistrar, srv FlightBookingSystemServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightBookingSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightBookingSystemService_ServiceDesc, srv)
}

// FlightBookingSystemService_ServiceDesc is the grpc.ServiceDesc for FlightBookingSystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightBookingSystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fbs.FlightBookingSystemService",
	HandlerType: (*FlightBookingSystemServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/flight.proto",
}
